name: Topos-Playground Build Docs

on:
  schedule:
    - cron:  '0 3 * * *'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download source
      uses: actions/checkout@v2
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
    - name: Install dependencies
      run: shards install
    - name: Build docs
      run: crystal docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
