name: Topos-Playground CI

on:
  schedule:
    - cron:  '0 3 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download source
      uses: actions/checkout@v2
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec -t -s
    - name: Format Linting
      run: crystal tool format --check
    - name: Run Ameba
      run: bin/ameba
