name: Topos-Playground Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Crystal
        run: brew install openssl crystal
      - name: Install dependencies
        run: shards install
      - name: Build the binary
        run: |
          ln -s /usr/lib/libxml2.2.dylib /usr/local/lib/liblibxml2.tbd.dylib
          shards build --release --stats --progress
      - name: Compress the binary
        run: zip -rjX ./topos-playground-darwin.zip ./bin/topos-playground
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: topos-playground-darwin
          path: ./topos-playground-darwin.zip

  build-macos-13:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Crystal
        run: brew install openssl crystal
      - name: Install dependencies
        run: shards install
      - name: Build the binary
        run: |
          ln -s /usr/lib/libxml2.2.dylib /usr/local/lib/liblibxml2.tbd.dylib
          shards build --release --stats --progress
      - name: Compress the binary
        run: zip -rjX ./topos-playground-darwin.zip ./bin/topos-playground
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: topos-playground-darwin-macos13
          path: ./topos-playground-darwin-macos13.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install dependencies
        run: shards install
      - name: Build the binary
        run: |
          shards build --release --static --stats --progress
      - name: Compress the binary
        run: |
          gzip -9 ./bin/topos-playground
          mv ./bin/topos-playground.gz ./bin/topos-playground-linux-x86_64.gz
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: topos-playground-linux-x86_64
          path: ./bin/topos-playground-linux-x86_64.gz

  release:
    needs: [build-macos, build-linux, build-macos-13]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./artifacts/topos-playground-darwin/topos-playground-darwin.zip
            ./artifacts/topos-playground-darwin-macos13/topos-playground-darwin-macos13.zip
            ./artifacts/topos-playground-linux-x86_64/topos-playground-linux-x86_64.gz
          token: ${{ secrets.GITHUB_TOKEN }}
